name: Loadbalancer Deploy
description: Deploy an AWS Loadbalancer using Terraform
inputs:
  protocol:
    description: 'Loadbalancer Protocol'
    default: 'HTTPS'
    required: true

outputs:
  arn:
    description: 'Elasticsearch service ARN'
  endpoint:
    description: 'Elasticsearch service endpoint'
  kibana_endpoint:
    description: 'Elasticsearch service Kibana endpoint'
  access_policy_arn:
    description: 'ARN of policy granting access to this ES instance'
  access_policy_name:
    description: 'Name of policy granting access to this ES instance'

runs:
  using: docker
  image: Dockerfile
